Add documentation
ballerina-platform/module-ballerinax-spotify pull request #6
Opened 2024-12-06 16:24 UTC by Sachindu-Nethmin

## Purpose

## Examples

## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests
- [x] Updated the spec
- [ ] Checked native-image compatibility

2024-12-09 06:12 UTC, aashikam approved these changes, later dismissed
LGTM

2024-12-09 18:13 UTC, NipunaRanasinghe requested changes

2024-12-09 18:13 UTC, NipunaRanasinghe commented on README.md
> +### Step 2: Set up user authentication settings
As a convention we use sentence case for all the headings in documentation. Please apply same for all the headers
```suggestion
### Step 1: Create a Spotify developer project

1. Open the [Spotify Developer Portal](https://developer.spotify.com/dashboard).
<img src=https://raw.githubusercontent.com/ballerina-platform/module-ballerinax-spotify/main/docs/setup/resources/dashboad.png alt="Dashboad" style="width: 70%;">


2. Click on the "Create an app" tab and select an existing project or create a new one for which you want API Keys and Authentication Tokens.
<img src=https://raw.githubusercontent.com/ballerina-platform/module-ballerinax-spotify/main/docs/setup/resources/app_overview.png alt="Spotify Developer Portal" style="width: 70%;">


### Step 2: Set up user authentication settings
```

2024-12-09 18:13 UTC, NipunaRanasinghe commented on README.md
> +Now, utilize the available connector operations.
We need to add a simple Ballerina code in here to demonstrate a most basic and simple use case. 

Refer to the below sample related to the twitter connector
<img width="1019" alt="Screenshot 2024-12-09 at 23 37 34" src="https://github.com/user-attachments/assets/b86b60f8-0793-4bb3-a1cf-fea66fba4e42">

2024-12-09 19:02 UTC, Sachindu-Nethmin commented
@NipunaRanasinghe  need review.

2024-12-10 03:41 UTC, NipunaRanasinghe approved these changes

2024-12-10 03:41 UTC, merged