Add example
ballerina-platform/module-ballerinax-spotify pull request #7
Opened 2024-12-10 18:41 UTC by Sachindu-Nethmin

## Purpose

## Examples

## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Updated the spec
- [ ] Checked native-image compatibility

2024-12-11 04:18 UTC, ayeshLK commented on examples/get-markets/main.bal
> +    MarketsResponse|error response = spotify->/markets;
```suggestion
    MarketsResponseresponse = check spotify->/markets;
```

2024-12-15 01:25 UTC, Sachindu-Nethmin commented
@ayeshLK  need review.

2024-12-15 02:55 UTC, NipunaRanasinghe requested changes
@Sachindu-Nethmin requested some changes

2024-12-15 02:55 UTC, NipunaRanasinghe commented on examples/get-markets/README.md
> +This use case demonstrates how the Spotify API can be utilized to create a new folder in your Spotify account.
Here the example is about getting the available spotify markets, but the documentation say its about creating a folder (which is incorrect). so we either have to update the documentation or the code to be in sync.

btw I prefer having a more real example for this connector which includes 2-3 API calls in a meaningful way. We have added examples in the other connectors in the same way.

2025-01-07 05:10 UTC, ThisaruGuruge approved these changes

2025-01-07 05:11 UTC, closed without merging

2025-01-07 05:11 UTC, ThisaruGuruge commented
Closing the PR since the author has not responded for some time. Please re-open if you are free to work on this.